### ISSUE TITLE
len() built-in produces incorrect results

### ISSUE THREAD

**Issue by skx** [pandeykartikey/goto#4]
I had this issue with [my overhauled/enhanced version of monkey](https://github.com/skx/monkey/), so it was the first thing I looked for:

Sample program:

```
cat len.goto
print( len( "狐犬" ) );
```

Execution:

```
goto len.goto 
6
null
```

You want to change your primitive to use something like this:

```
return &object.Integer{Value: int64(utf8.RuneCountInString(arg.Value))}
```

Rather than:

```
return &object.Integer{Value: int64(len(arg.Value))}
```

**Comment by pandeykartikey** [comment]
Thanks for pointing this out. I never tested for characters other than English alphabets.
